pipeline {
    agent any
    tools {
        nodejs 'NodeJS 10.8.0' 
        type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        env.PATH = "${node}/bin:${env.PATH}"
    }
    stages {
        stage('Check Installations') {
            steps {
                //sh 'mvn --version'
                sh 'java -version'
                sh 'git --version'
                sh 'docker --version'
                sh 'npm --version'
                sh 'node --version'
                
            }
        }
    stage('Build Maven Package'){
            steps{
                sh 'npm install'
            }
        }
       
    }
}