pipeline {
    agent any
    tools {
        node 'node10.30' 
    }
    stages {
        stage('Check Installations') {
            steps {
                //sh 'mvn --version'
                sh 'java -version'
                sh 'git --version'
                sh 'docker --version'
                sh 'node --version'
                sh 'npm --version'
                
            }
        }
    stage('Build Maven Package'){
            steps{
                sh 'npm install'
            }
        }
       
    }
}